`timescale 1ns/1ps
//============================================================================
// fir_accel.v
// Transposed-form, fully pipelined FIR filtering accelerator.
//   - Q1.15 fixed-point samples and coefficients
//   - one output sample per clock (latency = 2 cycles)
//   - AXI4-Stream input/output handshake
// Coefficients are loaded from "coeffs.hex" (generated by scripts/gen_coeffs.py).
//============================================================================
module fir_accel #(
  parameter integer N_TAPS  = 31,
  parameter integer DATA_W  = 16,   // Q1.15 sample width
  parameter integer COEFF_W = 16,   // Q1.15 coefficient width
  parameter integer ACC_W   = 40    // accumulator width (guard bits)
)(
  input  wire                     clk,
  input  wire                     rst_n,
  // AXI4-Stream slave (input samples)
  input  wire signed [DATA_W-1:0] s_axis_tdata,
  input  wire                     s_axis_tvalid,
  output wire                     s_axis_tready,
  // AXI4-Stream master (filtered output)
  output wire signed [DATA_W-1:0] m_axis_tdata,
  output wire                     m_axis_tvalid,
  input  wire                     m_axis_tready   // assumed always ready (see Future work)
);

  // ---- coefficients (Q1.15), loaded from coeffs.hex ----
  reg signed [COEFF_W-1:0] h [0:N_TAPS-1];
  initial $readmemh("coeffs.hex", h);

  assign s_axis_tready = 1'b1;            // always ready
  wire fire = s_axis_tvalid & s_axis_tready;

  // ---- transposed-form accumulator chain ----
  reg signed [ACC_W-1:0] r [0:N_TAPS-1];
  integer i;
  always @(posedge clk) begin
    if (!rst_n) begin
      for (i = 0; i < N_TAPS; i = i + 1) r[i] <= {ACC_W{1'b0}};
    end else if (fire) begin
      r[N_TAPS-1] <= s_axis_tdata * h[N_TAPS-1];
      for (i = 0; i < N_TAPS-1; i = i + 1)
        r[i] <= r[i+1] + s_axis_tdata * h[i];
    end
  end

  // ---- round (Q2.30 -> Q1.15) + saturate ----
  localparam signed [ACC_W-1:0] RND  = (1 <<< 14);   // 0.5 LSB
  localparam signed [ACC_W-1:0] MAXV =  32767;
  localparam signed [ACC_W-1:0] MINV = -32768;
  wire signed [ACC_W-1:0] acc_r = (r[0] + RND) >>> 15;
  wire signed [DATA_W-1:0] y_sat =
        (acc_r > MAXV) ? MAXV[DATA_W-1:0] :
        (acc_r < MINV) ? MINV[DATA_W-1:0] : acc_r[DATA_W-1:0];

  // ---- registered output + 2-stage valid pipeline ----
  reg signed [DATA_W-1:0] y_q;
  reg v1, v2;
  always @(posedge clk) begin
    if (!rst_n) begin v1 <= 1'b0; v2 <= 1'b0; y_q <= {DATA_W{1'b0}}; end
    else begin
      v1  <= fire;
      y_q <= y_sat;
      v2  <= v1;
    end
  end
  assign m_axis_tdata  = y_q;
  assign m_axis_tvalid = v2;

endmodule
